// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxf9zPFWoTFmhSVsxxR3zCkDXHTjAxBEQ',
    appId: '1:1018984691004:web:6a3dd89361106498a1da39',
    messagingSenderId: '1018984691004',
    projectId: 'ict-connect-firebase-fc5fa',
    authDomain: 'ict-connect-firebase-fc5fa.firebaseapp.com',
    storageBucket: 'ict-connect-firebase-fc5fa.appspot.com',
    measurementId: 'G-PTF4G0WRS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Q617NxboUHWxdepQivljLDJv0n96YF0',
    appId: '1:1018984691004:android:ede7978e73651823a1da39',
    messagingSenderId: '1018984691004',
    projectId: 'ict-connect-firebase-fc5fa',
    storageBucket: 'ict-connect-firebase-fc5fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVZk_vq5zCijRyxUyTf41a_T5OOOAnp5M',
    appId: '1:1018984691004:ios:bda8b6dff0a0a9d2a1da39',
    messagingSenderId: '1018984691004',
    projectId: 'ict-connect-firebase-fc5fa',
    storageBucket: 'ict-connect-firebase-fc5fa.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
